/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FERRETERIA;

/**
 *
 * @author renzo
 */
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class REGISTRO_PROVEEDOR extends javax.swing.JFrame {

    /**
     * Creates new form REGISTRO_PROVEEDOR
     */
    public REGISTRO_PROVEEDOR() {
        initComponents();
        setLocationRelativeTo(null);
        txtCodProveedor.setVisible(false);
        cargarTabla();
        this.cboDistritoProveedor.removeAllItems();
        try{
             Connection con = PRINCIPAL.getPRINCIPAL();
             Statement Sent = con.createStatement();
             ResultSet rs = Sent.executeQuery("Select * from DISTRITO");
             while(rs.next()){
                 this.cboDistritoProveedor.addItem(rs.getString("nom_dis"));
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCelularProveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        btnSalirProveedor = new javax.swing.JButton();
        txtCodProveedor = new javax.swing.JTextField();
        btnRegistrarProveedor = new javax.swing.JButton();
        btnModificarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        cboDistritoProveedor = new javax.swing.JComboBox<>();
        txtNombreProveedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO PROVEEDOR");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("CELULAR:");

        jLabel4.setText("DISTRITO:");

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CELULAR", "DISTRITO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedor);

        btnSalirProveedor.setText("SALIR");
        btnSalirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProveedorActionPerformed(evt);
            }
        });

        btnRegistrarProveedor.setText("REGISTRAR");
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });

        btnModificarProveedor.setText("MODIFICAR");
        btnModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProveedorActionPerformed(evt);
            }
        });

        btnEliminarProveedor.setText("ELIMINAR");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });

        cboDistritoProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalirProveedor)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCelularProveedor)
                            .addComponent(cboDistritoProveedor, 0, 87, Short.MAX_VALUE)
                            .addComponent(txtNombreProveedor))
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCodProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCodProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCelularProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboDistritoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirProveedor)
                    .addComponent(btnEliminarProveedor)
                    .addComponent(btnModificarProveedor)
                    .addComponent(btnRegistrarProveedor))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProveedorActionPerformed
        // TODO add your handling code here:
        dispose();
        //MENU_PRINCIPAL menu = new MENU_PRINCIPAL();
        //menu.setVisible(true);
    }//GEN-LAST:event_btnSalirProveedorActionPerformed

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
        String nom_prov = txtNombreProveedor.getText();
        int celular = Integer.parseInt(txtCelularProveedor.getText());
        String cod_dis = (String) cboDistritoProveedor.getSelectedItem();
        
        try{
            Connection con = PRINCIPAL.getPRINCIPAL();
            PreparedStatement ps = con.prepareStatement("INSERT INTO PROVEEDOR (nom_prov,celular,cod_dis,activo) VALUES(?,?,(select cod_dis from DISTRITO where nom_dis=?),?)");
            ps.setString(1, nom_prov);
            ps.setInt(2, celular);
            ps.setString(3,cod_dis);
            ps.setInt(4, 1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Proveedor Registrado");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        try{
            int fila = tblProveedor.getSelectedRow();
            int cod_prov = Integer.parseInt(tblProveedor.getValueAt(fila, 0).toString());
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = PRINCIPAL.getPRINCIPAL();
            ps = con.prepareStatement("SELECT nom_prov,celular,cod_dis FROM PROVEEDOR WHERE cod_prov=?");
            ps.setInt(1, cod_prov);
            rs = ps.executeQuery();
            
            while(rs.next()){
                txtCodProveedor.setText(String.valueOf(cod_prov));
                txtNombreProveedor.setText(rs.getString("nom_prov"));
                txtCelularProveedor.setText(String.valueOf(rs.getString("celular")));
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblProveedorMouseClicked

    private void btnModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProveedorActionPerformed
        int cod_prov =Integer.parseInt(txtCodProveedor.getText());
        String nom_prov = txtNombreProveedor.getText();
        int celular = Integer.parseInt(txtCelularProveedor.getText());
        String cod_dis = (String) cboDistritoProveedor.getSelectedItem();
        
        try{
            Connection con = PRINCIPAL.getPRINCIPAL();
            PreparedStatement ps = con.prepareStatement("UPDATE PROVEEDOR SET nom_prov=?,celular=?,cod_dis=? WHERE cod_prov=?");
            ps.setString(1, nom_prov);
            ps.setInt(2, celular);
            ps.setString(3, cod_dis);
            ps.setInt(4, cod_prov);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Proveedor Modificado");
            limpiar();
            cargarTabla();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_btnModificarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        int cod_prov =Integer.parseInt(txtCodProveedor.getText());

        try{
            Connection con = PRINCIPAL.getPRINCIPAL();
            PreparedStatement ps = con.prepareStatement("UPDATE PROVEEDOR SET activo=0 WHERE cod_prov=?");
            ps.setInt(1,cod_prov);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "PROVEEDOR ELIMINADO");
            limpiar();
            cargarTabla();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed
    
    private void limpiar(){
        txtNombreProveedor.setText("");
        txtCelularProveedor.setText("");
    }
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblProveedor.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try{
            Connection con = PRINCIPAL.getPRINCIPAL();
            ps = con.prepareStatement("SELECT cod_prov,nom_prov,celular,distrito.nom_dis FROM PROVEEDOR inner join DISTRITO on distrito.cod_dis=proveedor.cod_dis WHERE proveedor.activo=1");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice=0;indice<columnas;indice++){
                    fila[indice]= rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PROVEEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PROVEEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PROVEEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_PROVEEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRO_PROVEEDOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnModificarProveedor;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JButton btnSalirProveedor;
    private javax.swing.JComboBox<String> cboDistritoProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtCelularProveedor;
    private javax.swing.JTextField txtCodProveedor;
    private javax.swing.JTextField txtNombreProveedor;
    // End of variables declaration//GEN-END:variables
}
